### PR TITLE
Add contrib sub directory to dash.js webjar

### PR DESCRIPTION
**Pull request by mouhb**

### CODE REVIEW

**Comment by jamesward** [comment]
Usually we like to make these kinds of things into declared transitive dependencies so that an artifact only has a single version of a single artifact in it.  Would that work for you?

**Comment by mouhb** [comment]
I don't understand exactly what you mean by ' make these kinds of things into declared transitive dependencies'. Please explain.

**Comment by jamesward** [comment]
At first glance these looked like external dependencies that should be specified as such.  But looking closer they aren't.  So your approach is fine.

**Comment by mouhb** [comment]
Thank you.

**Comment by jamesward** [comment]
This will be released shortly as `1.5.1-1`.

**Pull request merged**
